### ISSUE TITLE
Exception when running minified jar for compose project

### ISSUE THREAD

**Issue by sebkur** [sebkur/test-proguard#1]
After building the minified jar using `./gradlew minify --info` from the `compose` project directory:

```
$ java -jar build/compose/jars/Test-linux-x64-1.0.0.min.jar 
Test
pid: 454379
java.lang.NoSuchMethodError: commitLine
        at org.jetbrains.skia.impl.Library._nAfterLoad(Native Method)
        at org.jetbrains.skia.impl.Library$Companion._nAfterLoad(Library.jvm.kt)
        at org.jetbrains.skiko.Library.load(Library.kt:66)
        at org.jetbrains.skiko.SkiaLayer.<clinit>(SkiaLayer.jvm.kt:29)
        at androidx.compose.ui.awt.ComposeLayer.<init>(ComposeLayer.desktop.kt:73)
        at androidx.compose.ui.awt.ComposeWindowDelegate.<init>(ComposeWindowDelegate.desktop.kt:44)
        at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:47)
        at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:44)
        at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:161)
        at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:156)
        at androidx.compose.ui.window.Window_desktopKt$Window$10$1.invoke(Window.desktop.kt:367)
        at androidx.compose.ui.window.Window_desktopKt$Window$10$1.invoke(Window.desktop.kt:366)
        at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:75)
        at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:74)
        at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
        at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:802)
        at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:647)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:763)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:433)
        at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:220)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The app runs fine though:

![Screenshot from 2022-02-02 11-59-49](https://user-images.githubusercontent.com/1633488/152141435-58d20d8f-fb95-44be-9c75-852eff6ce3e5.png)

**Comment by sebkur** [comment]
Fixed with 87657d545992efbbe98003ed8c9b78efef8f7f4c
